### ISSUE TITLE
Is there a way to force refresh?

### ISSUE THREAD

**Issue by mjsarfatti** [Synvox/api#2]
This is my situation:

In my Create React App I have one page with the a list of form submissions, and a second page with the form itself. Plus a home page.
They are under different React Router routes.

```bash
/              # The home page
/submit-visit  # Contains the form to send a new submission
/visits        # Displays a table with the list of submissions
```

When I open the app on `/visits` a request is sent ( `const visits = api.visits(params);`), a spinner shows up (thanks to Suspense), and a little later the submissions fill my table. Here is a pseudocode for the page `/visits`:

```js

const Visits = () => {
  return (
    <Suspense fallback={<p>Loading...</p>}>
      <List />
    </Suspense>
  );
}

const List = () => {
  const api = useApi();

  // This logs every time I navigate to /visits, so I know for sure that this component
  // is being re-rendered. But only on the first navigation is /api/visits actually called.
  console.log('fetching'); 

  const visits = api.visits();

  return (
    <ul>
      {visits.data.map(visit => <li>{visit.id} {visit.title}</li>)}
    </ul>
  );
}
```

Now, when the user navigates to `/submit-visit` and fills and sends the form, upon success he/she is redirected to `/visits`. But they still see the stale list, no new network request is sent.

What I think happens here is that `api` sees that I've already called `GET /api/visits`, reads the cache, and gives me a stale list of submissions. I have to reload the page using the browser button to get the freshly sent form.

How can I force `api` to refresh even if the request is in the cache?  
Maybe `touch` is what I need? But I can't figure out where I'm supposed to call it... If I call it right after `api.visits()` am I going to fetch the same route twice on app load?

**Comment by Synvox** [comment]
@mjsarfatti 

You're right, you need to call `await touch('visits')` to invalidate the cache. I'd recommend doing this right after your form submit.

```
async function onSubmit(){
  // do your form submit
  await touch('visits')
  history.push('/visits')
}
```

Would probably do what you're looking for.
