### ISSUE TITLE
Does not work with IE11

### ISSUE THREAD

**Issue by mjsarfatti** [Synvox/api#3]
I'm leaving this here just in case it saves some time to others, not because I expect a fix.

This library makes use of `Proxy`, which is supported only starting with Edge 12, and is basically non-polyfillable in IE11.

I had a quick look at the source code and it looks like the whole API of this library depends on `Proxy`. If the author were to make it compatible he would have to basically re-write the whole thing and it wouldn't work the way it works now anyway.

**Comment by Synvox** [comment]
This is true. This library aims to support the same browsers that immer, mobx, and react-easy-state support. These React libraries also rely heavily on `Proxy`.
